proxy:
  title: MS-Nutrition Shiny applications
  port: 8080

  container-wait-time: 30000
  heartbeat-rate: 10000
  heartbeat-timeout: 60000

  authentication: simple

  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password

  docker:
      internal-networking: true

  specs:
  - id: Breakfast
    display-name: Breakfast
    description: Application pour évaluer ton petit-déjeuner
    container-cmd: ["R", "-e", "shiny::runApp('/root/breakfast_demo')"]
    container-image: rzngzn/bkfst:latest
    container-network: sp-net

logging:
  file:
    /log/shinyproxy.log

